### ISSUE TITLE
Research how to publish the APP to the Google Playstore

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/repair-tool#34]
## Tasks

- [x] Do we need a Google Account?
- [x] Analyse and describe howto publish into playstore

**Comment by MiKessels** [comment]
This is a good tutorial on how to publish our Android APP [YouTube](https://www.youtube.com/watch?v=ieWtCaWkzYQ&t=11s)
On this website you can signup for a developer account, I think it's recommended to create a new developer account just for KA-huis. The costs are $25 paid by credit card. [Google Play Console](https://play.google.com/console/signup)
