### ISSUE TITLE
Create overview on all repairs

### ISSUE THREAD

**Issue by MiKessels** [KA-Huis/repair-tool#38]
The overview must contain a list of all repairs already reported

**Comment by MiKessels** [comment]
Overview created, but now in comments so I don't overload the API requests while testing.

**Comment by cyrildewit** [comment]
@MiKessels when was ticket reviewed by other members of the team? Did someone tested the acceptance criteria? I think your pull request is also still open, so this ticket can logically not be moved to done.

Do you know about the `Definition of Done`? It's a term from Scrum, but it basically means: When can a ticket be considered done? This is usually loosely defined within a team. Right now it means that the acceptance criteria has been met and it's released.
