### ISSUE TITLE
Create mock server in Postman

### ISSUE THREAD

**Issue by MiKessels** [KA-Huis/repair-tool#41]
Create a Mock server in Postman to test the API inside the android app.

**Comment by MiKessels** [comment]
@Hoopless @cyrildewit I created a MOCK server in postman for testing my app. I'm new to API/ Postman, if one of you can look at my MOCK that would be great.
I will transfer the mock data from my postman account to our team account. You can find it under the AndroidApp workspace.

**Comment by cyrildewit** [comment]
@MiKessels great. Thank you for bringing us up to date.
