### ISSUE TITLE
Connectie database

### ISSUE THREAD

**Issue by MiKessels** [KA-Huis/repair-tool#6]
Als er een connectie is met een database is de lijst met klussen altijd up to date.

**Comment by MiKessels** [comment]
First look at FireBase as a solution

**Comment by cyrildewit** [comment]
@MiKessels I suppose the objective of this ticket will change to write a client to consume the REST API of the Space Management application?

See https://github.com/KA-Huis/space-management/issues/37 for the current status. FYI it's currently blocked.
